packages:
    - ./package
    - ./test
    - ./examples/*

autoInstallPeers: false
strictPeerDependencies: false

allowBuilds:
    esbuild: false
    sharp: true

catalogs:
    dep:
        "@standard-schema/spec": ^1.1.0
    dev:
        arktype: 2.2.0
        valibot: 1.4.0
        zod: 4.4.0
    peer:
        arktype: ^2.2.0
        valibot: ^1.4.0
        zod: ^4.4.0
    example:
        "@types/react": ^19.2.17
        "@types/react-dom": ^19.2.3
        react: ^19.2.7
        react-dom: ^19.2.7
        next: 16.2.9
        vite: ^8.0.16

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
    - "@apst/*"
    - "@typescript/*"
    - typescript
